// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// jaeckel
double jaeckel(double price, double forward, double strike, double time, bool call);
RcppExport SEXP _implvol_jaeckel(SEXP priceSEXP, SEXP forwardSEXP, SEXP strikeSEXP, SEXP timeSEXP, SEXP callSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type price(priceSEXP);
    Rcpp::traits::input_parameter< double >::type forward(forwardSEXP);
    Rcpp::traits::input_parameter< double >::type strike(strikeSEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    Rcpp::traits::input_parameter< bool >::type call(callSEXP);
    rcpp_result_gen = Rcpp::wrap(jaeckel(price, forward, strike, time, call));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_implvol_jaeckel", (DL_FUNC) &_implvol_jaeckel, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_implvol(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
