# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jaeckel <- function(price, forward, strike, time, call) {
    .Call('_implvol_jaeckel', PACKAGE = 'implvol', price, forward, strike, time, call)
}

