# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

implvol <- function(price, F, K, T, q) {
    .Call(`_implvol_implvol`, price, F, K, T, q)
}

